CREATE TABLE IF NOT EXISTS wb_weekly_reports (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  store_id uuid NOT NULL REFERENCES stores(id),
  report_number bigint NOT NULL,
  legal_entity text,
  date_from date,
  date_to date,
  date_created date,
  report_type text,
  sale numeric(15,2),
  loyalty_compensation numeric(15,2),
  for_pay numeric(15,2),
  agreed_discount_pct numeric(8,4),
  logistics_cost numeric(15,2),
  storage_cost numeric(15,2),
  acceptance_cost numeric(15,2),
  other_deductions numeric(15,2),
  total_fines numeric(15,2),
  wb_commission_correction numeric(15,2),
  loyalty_program_cost numeric(15,2),
  loyalty_points_deducted numeric(15,2),
  one_time_payment_change numeric(15,2),
  total_to_pay numeric(15,2),
  currency text,
  has_detail_rows boolean DEFAULT false,
  reconciled boolean DEFAULT false,
  reconciled_at timestamptz,
  reconcile_result jsonb,
  created_at timestamptz DEFAULT now(),
  UNIQUE (store_id, report_number)
);

CREATE TABLE IF NOT EXISTS wb_weekly_report_rows (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  store_id uuid NOT NULL REFERENCES stores(id),
  report_number bigint NOT NULL,
  row_number int,
  supply_number text,
  subject text,
  nm_id bigint,
  brand text,
  supplier_article text,
  title text,
  techsize text,
  barcode text,
  doc_type text,
  payment_reason text,
  order_date date,
  sale_date date,
  quantity int,
  retail_price numeric(15,2),
  wb_sale_amount numeric(15,2),
  agreed_product_discount_pct numeric(8,4),
  promo_code_pct numeric(8,4),
  total_agreed_discount_pct numeric(8,4),
  retail_price_with_discount numeric(15,2),
  kvv_rating_reduction_pct numeric(8,4),
  kvv_promo_change_pct numeric(8,4),
  platform_discounts_pct numeric(8,4),
  kvv_pct numeric(8,4),
  kvv_base_excl_vat_pct numeric(8,4),
  kvv_final_excl_vat_pct numeric(8,4),
  commission_before_agent_excl_vat numeric(15,6),
  pvz_compensation numeric(15,6),
  payment_service_compensation numeric(15,6),
  payment_service_compensation_pct numeric(8,4),
  payment_service_type text,
  wb_commission_excl_vat numeric(15,6),
  wb_commission_vat numeric(15,6),
  for_pay_seller numeric(15,6),
  deliveries_count int,
  returns_count int,
  delivery_service_cost numeric(15,6),
  fix_start_date date,
  fix_end_date date,
  paid_delivery_flag text,
  total_fines numeric(15,6),
  wb_commission_correction numeric(15,6),
  logistics_fines_types text,
  sticker text,
  acquirer_bank text,
  office_number text,
  office_name text,
  partner_inn text,
  partner text,
  warehouse text,
  country text,
  box_type text,
  customs_declaration_number text,
  assembly_task_number text,
  marking_code text,
  barcode_sticker text,
  srid text,
  transport_compensation numeric(15,6),
  transport_organizer text,
  row_storage_cost numeric(15,6),
  deductions numeric(15,6),
  acceptance_operations numeric(15,6),
  chrt_id bigint,
  fixed_warehouse_coef numeric(15,6),
  legal_entity_sale_flag text,
  tmc text,
  box_number text,
  cofinancing_discount numeric(15,6),
  wibes_discount_pct numeric(8,4),
  loyalty_discount_compensation numeric(15,6),
  loyalty_program_cost numeric(15,6),
  loyalty_points_deducted numeric(15,6),
  basket_id text,
  one_time_payment_change numeric(15,6),
  sale_method_type text,
  seller_promo_id text,
  seller_promo_discount_pct numeric(8,4),
  seller_loyalty_discount_id text,
  seller_loyalty_discount_pct numeric(8,4),
  promo_code_id text,
  promo_code_discount_pct numeric(8,4),
  substitution_article_id text,
  substitution_article_discount_pct numeric(8,4),
  wholesale_discount_pct numeric(8,4),
  created_at timestamptz DEFAULT now(),
  UNIQUE (store_id, report_number, srid)
);
